#!/bin/bash
# Called by dnsmasq on DHCP lease events.
# Args: $1=action (add|old|del), $2=mac, $3=ip, $4=hostname
#
# Since the PDU is the only device on eth1, any lease event means
# we've found (or lost) the PDU. Write its IP for nginx and ssh-bridge.

ACTION="$1"
MAC="$2"
IP="$3"
PDU_IP_FILE="/var/run/pdu_ip"
NGINX_UPSTREAM="/etc/nginx/conf.d/pdu-upstream.conf"

case "$ACTION" in
    add|old)
        echo "$IP" > "$PDU_IP_FILE"

        # Regenerate nginx upstream and reload
        cat > "$NGINX_UPSTREAM" <<EOF
# Auto-generated by pdu-lease-hook — do not edit
upstream pdu_backend {
    server ${IP}:%%PDU_HTTPS_PORT%%;
}
EOF
        nginx -t 2>/dev/null && systemctl reload nginx
        ;;
    del)
        rm -f "$PDU_IP_FILE"
        ;;
esac
